### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shinumani** [isaacs/isexe#27]
error is comin.please help
code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\Joby\\Desktop\\Blog-Website\\client\\node_modules\\isexe\\package.json',
  requestPath: 'isexe'

**Comment by shinumani** [comment]
Error: Cannot find module 'C:\Users\joby\Desktop\Blog-Website\client\node_modules\isexe\index.js'. Please verify that the package.json has a valid "main" entry

**Comment by SergeySharashkin** [comment]
admin@PC2 MINGW64 /f/Projects/goit-react-hw-04-hooks-feedback (main)
$ npm run start

> goit-react-hw-04-hooks-feedback@0.1.0 start
> react-scripts start

internal/modules/cjs/loader.js:328
      throw err;
      ^

Error: Cannot find module 'F:\Projects\goit-react-hw-04-hooks-feedback\node_modules\isexe\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:320:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:533:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:875:27)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (F:\Projects\goit-react-hw-04-hooks-feedback\node_modules\which\which.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'F:\\Projects\\goit-react-hw-04-hooks-feedback\\node_modules\\isexe\\package.json',
  requestPath: 'isexe'
}

**Comment by Bholaji** [comment]
Error: Cannot find module 'C:\Users\Bholaji\Documents\Taooja\auth-app\node_modules\isexe\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:353:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Bholaji\Documents\Taooja\auth-app\node_modules\which\which.js:7:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\Bholaji\\Documents\\Taooja\\auth-app\\node_modules\\isexe\\package.json',
  requestPath: 'isexe'
}
